// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisvXyuQxEeqBoW_aZWvofMiepQFf5tdw',
    appId: '1:241634317459:web:0e25b7cc4d5fff89a26966',
    messagingSenderId: '241634317459',
    projectId: 'shiftsmart-39f39',
    authDomain: 'shiftsmart-39f39.firebaseapp.com',
    storageBucket: 'shiftsmart-39f39.firebasestorage.app',
    measurementId: 'G-1NZD8N69ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6iXDDYsTao2X1X0pnXDUizcf9XvZk2w',
    appId: '1:241634317459:android:c79260dab3bd0348a26966',
    messagingSenderId: '241634317459',
    projectId: 'shiftsmart-39f39',
    storageBucket: 'shiftsmart-39f39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxRW9WMUNfNhGysP8EwhtXY3a29OESDgA',
    appId: '1:241634317459:ios:45f561690b89b61aa26966',
    messagingSenderId: '241634317459',
    projectId: 'shiftsmart-39f39',
    storageBucket: 'shiftsmart-39f39.firebasestorage.app',
    iosBundleId: 'com.rezan.shiftsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxRW9WMUNfNhGysP8EwhtXY3a29OESDgA',
    appId: '1:241634317459:ios:613335bfecf1d8a8a26966',
    messagingSenderId: '241634317459',
    projectId: 'shiftsmart-39f39',
    storageBucket: 'shiftsmart-39f39.firebasestorage.app',
    iosBundleId: 'com.example.shiftsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAisvXyuQxEeqBoW_aZWvofMiepQFf5tdw',
    appId: '1:241634317459:web:6c06a986a61ae431a26966',
    messagingSenderId: '241634317459',
    projectId: 'shiftsmart-39f39',
    authDomain: 'shiftsmart-39f39.firebaseapp.com',
    storageBucket: 'shiftsmart-39f39.firebasestorage.app',
    measurementId: 'G-G04NDTR82R',
  );
}
